#include "GFLhelpers.as"

const array<SoldierInfo@> sf_eazymode_weight =
{
    SoldierInfo("sf_vespid",3.0),
    SoldierInfo("sf_vespid_swap",2.0),
    SoldierInfo("sf_vespid_vehicle_user",0.8),
    SoldierInfo("sf_ripper",3.0),
    SoldierInfo("sf_ripper_swap",1.0),
    SoldierInfo("sf_guard",1.5),
    SoldierInfo("sf_guard_swap",0.1),
    SoldierInfo("sf_jaeger",1.0),
    SoldierInfo("sf_jaeger_swap",0.4),
    SoldierInfo("sf_striker",1.5),
    SoldierInfo("sf_striker_swap",0.5),
    SoldierInfo("sf_nemeum",0.2),
    SoldierInfo("sf_nemeum_swap",0.05),
    SoldierInfo("sf_jaguar",0.5),
    SoldierInfo("sf_prowler",2.0),
    SoldierInfo("sf_prowler_swap",1.0),
    SoldierInfo("sf_aegis",0.1),
    SoldierInfo("sf_aegis_swap",0.05),
    SoldierInfo("sf_dragoon",0.2),
    SoldierInfo("sf_dragoon_swap",0.1),
    SoldierInfo("sf_brute",0.8),
    SoldierInfo("sf_brute_swap",0.3),
    SoldierInfo("sf_hunter",0.01),
    SoldierInfo("sf_architect",0.01),
    SoldierInfo("sf_intruder",0.01),
    SoldierInfo("sf_dreamer",0.01),
    SoldierInfo("sf_alchemist",0.01),
    SoldierInfo("sf_gager",0.01),
    SoldierInfo("sf_executioner_wind_rose",0.005),
    SoldierInfo("sf_executioner_queen_of_the_moon",0.005),
    SoldierInfo("sf_m16a1",0.01),
    SoldierInfo("sf_agent",0.01),
    SoldierInfo("sf_destroyer",0.01),
    SoldierInfo("sf_weaver",0.01),
    SoldierInfo("sf_justice",0.01),
    SoldierInfo("sf_scarecrow",0.01),
    SoldierInfo("sf_manticore",0.02),
    SoldierInfo("sf_dinergate",1.0),
    SoldierInfo("sf_tarantula",1.0),
    SoldierInfo("sf_cerberus",0.005),
    SoldierInfo("sf_scouts",2.0),
    SoldierInfo("sf_goliath",0.02),
    SoldierInfo("sf_goliath_plus",0.01)
};

const array<SoldierInfo@> paradeus_eazymode_weight =
{
    SoldierInfo("pard_strelet",4.0),
    SoldierInfo("pard_streletplus",2.0),
    SoldierInfo("pard_rodelero",0.1),
    SoldierInfo("pard_commander",0.2),
    SoldierInfo("pard_police",1.0),
    SoldierInfo("pard_hammer",0.1),
    SoldierInfo("pard_dog",0.1),
    SoldierInfo("pard_thrower",0.2),
    SoldierInfo("pard_grenadier",0.1),
    SoldierInfo("pard_defender",0.05),
    SoldierInfo("alina",0.01),
    SoldierInfo("teal",0.01),
    SoldierInfo("eagleyes",0.02),
    SoldierInfo("vanguard",0.02),
    SoldierInfo("aileron",0.02),
    SoldierInfo("wrath",0.02),
    SoldierInfo("nimogen",0.01),
    SoldierInfo("narciss",0.01),
    SoldierInfo("tareus",0.001),
    SoldierInfo("ladon",0.01),
    SoldierInfo("adeline",0.01),
    SoldierInfo("infected",0.0),
    SoldierInfo("smasher",0.1),
    SoldierInfo("pard_doppelsoldner",0.02),
    SoldierInfo("pard_roarer",0.02),
    SoldierInfo("pard_hannibal",0.01),
    SoldierInfo("pard_arachne",0.005),
    SoldierInfo("thunder",0.02)
};

const array<SoldierInfo@> kcco_eazymode_weight =
{
    SoldierInfo("kcco_ar",2.5),
    SoldierInfo("kcco_ar_human",1.5),
    SoldierInfo("kcco_ar_human_vehicle",2.5),
    SoldierInfo("kcco_ar_human_elite",0.2),
    SoldierInfo("kcco_sg",1.5),
    SoldierInfo("kcco_mg",1.5),
    SoldierInfo("kcco_talos",1.0),
    SoldierInfo("kcco_dog",1.5),
    SoldierInfo("kcco_archer",0.2),
    SoldierInfo("kcco_cerynitis",0.1),
    SoldierInfo("kcco_cerynitis_swap",0.05),
    SoldierInfo("kcco_aegis",0.1),
    SoldierInfo("kcco_dactyl",0.1),
    SoldierInfo("kcco_hydra",0.05),
    SoldierInfo("kcco_teslatrooper",0.02),
    SoldierInfo("kcco_human_sniper",0.02),
    SoldierInfo("kcco_quartz_ranger",0.02),
    SoldierInfo("kcco_zircon_squadleader",0.01),
    SoldierInfo("kcco_ar_human_tel",0.05)
};

const array<SoldierInfo@> sf_hardmode_weight =
{
    SoldierInfo("sf_vespid",2.0),
    SoldierInfo("sf_vespid_swap",2.0),
    SoldierInfo("sf_vespid_vehicle_user",0.8),
    SoldierInfo("sf_ripper",2.0),
    SoldierInfo("sf_ripper_swap",2.0),
    SoldierInfo("sf_guard",1.5),
    SoldierInfo("sf_guard_swap",1.5),
    SoldierInfo("sf_jaeger",1.5),
    SoldierInfo("sf_jaeger_swap",1.5),
    SoldierInfo("sf_striker",1.5),
    SoldierInfo("sf_striker_swap",1.5),
    SoldierInfo("sf_nemeum",1.0),
    SoldierInfo("sf_nemeum_swap",0.75),
    SoldierInfo("sf_jaguar",0.75),
    SoldierInfo("sf_prowler",1.0),
    SoldierInfo("sf_prowler_swap",1.0),
    SoldierInfo("sf_aegis",0.5),
    SoldierInfo("sf_aegis_swap",0.5),
    SoldierInfo("sf_dragoon",0.5),
    SoldierInfo("sf_dragoon_swap",0.5),
    SoldierInfo("sf_brute",0.5),
    SoldierInfo("sf_brute_swap",0.5),
    SoldierInfo("sf_hunter",0.2),
    SoldierInfo("sf_architect",0.2),
    SoldierInfo("sf_intruder",0.2),
    SoldierInfo("sf_dreamer",0.2),
    SoldierInfo("sf_alchemist",0.2),
    SoldierInfo("sf_gager",0.2),
    SoldierInfo("sf_executioner_wind_rose",0.1),
    SoldierInfo("sf_executioner_queen_of_the_moon",0.1),
    SoldierInfo("sf_m16a1",0.2),
    SoldierInfo("sf_agent",0.2),
    SoldierInfo("sf_destroyer",0.2),
    SoldierInfo("sf_weaver",0.2),
    SoldierInfo("sf_justice",0.2),
    SoldierInfo("sf_scarecrow",0.2),
    SoldierInfo("sf_manticore",0.5),
    SoldierInfo("sf_dinergate",0.2),
    SoldierInfo("sf_tarantula",0.2),
    SoldierInfo("sf_cerberus",0.05),
    SoldierInfo("sf_scouts",1.0),
    SoldierInfo("sf_goliath",0.1),
    SoldierInfo("sf_goliath_plus",0.05)
};

const array<SoldierInfo@> paradeus_hardmode_weight =
{
    SoldierInfo("pard_strelet",3.0),
    SoldierInfo("pard_streletplus",3.0),
    SoldierInfo("pard_rodelero",1.0),
    SoldierInfo("pard_commander",0.5),
    SoldierInfo("pard_police",0.5),
    SoldierInfo("pard_hammer",0.5),
    SoldierInfo("pard_dog",0.5),
    SoldierInfo("pard_thrower",0.5),
    SoldierInfo("pard_grenadier",1.0),
    SoldierInfo("pard_defender",0.75),
    SoldierInfo("alina",0.2),
    SoldierInfo("teal",0.1),
    SoldierInfo("eagleyes",0.25),
    SoldierInfo("vanguard",0.25),
    SoldierInfo("aileron",0.25),
    SoldierInfo("wrath",0.25),
    SoldierInfo("nimogen",0.1),
    SoldierInfo("narciss",0.1),
    SoldierInfo("tareus",0.05),
    SoldierInfo("ladon",0.1),
    SoldierInfo("adeline",0.2),
    SoldierInfo("infected",0.0),
    SoldierInfo("smasher",0.3),
    SoldierInfo("pard_doppelsoldner",0.5),
    SoldierInfo("pard_roarer",0.5),
    SoldierInfo("pard_hannibal",0.1),
    SoldierInfo("pard_arachne",0.1),
    SoldierInfo("thunder",0.5)
};

const array<SoldierInfo@> kcco_hardmode_weight =
{
    SoldierInfo("kcco_ar",3.0),
    SoldierInfo("kcco_ar_human",0.5),
    SoldierInfo("kcco_ar_human_vehicle",1.5),
    SoldierInfo("kcco_ar_human_elite",2.5),
    SoldierInfo("kcco_sg",2.0),
    SoldierInfo("kcco_mg",1.5),
    SoldierInfo("kcco_talos",1.0),
    SoldierInfo("kcco_dog",1.5),
    SoldierInfo("kcco_archer",1.0),
    SoldierInfo("kcco_cerynitis",2.0),
    SoldierInfo("kcco_cerynitis_swap",1.5),
    SoldierInfo("kcco_aegis",1.0),
    SoldierInfo("kcco_dactyl",0.5),
    SoldierInfo("kcco_hydra",0.5),
    SoldierInfo("kcco_teslatrooper",0.5),
    SoldierInfo("kcco_human_sniper",0.25),
    SoldierInfo("kcco_quartz_ranger",0.25),
    SoldierInfo("kcco_zircon_squadleader",0.25),
    SoldierInfo("kcco_ar_human_tel",0.5)
};


const array<Resource@> sf_vespid_resource = {
	Resource("sfw_vespid_swap.weapon", "weapon"),
    Resource("vest_15hp_elite.carry_item", "carry_item"),
    Resource("sfw_m2g.weapon", "weapon"),
    Resource("sf_ap_mine.projectile", "projectile")
};

